language: java
jdk: oraclejdk7
before_install:
  - pip install --user codecov
script: 
  - ./gradlew sodra-backend:build
  - ./gradlew sodra-backend:jacocoTestReport
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash) -f 'TEST-*.xml'